### ISSUE TITLE
challenge-error-and-exception-handling

### ISSUE THREAD

**Issue by GodsDusk** [labex-labs/scenarios#306]
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**:Error and Exception Handling
- **Suggest Steps 建议步骤数**:3
- **Suggest Image 建议环境**: `webide-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Reference Answers 参考答案
- [ ] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`python/unittest`**
- **`python/try_except`**
- **`python/unittest`**
- **`python/raise_errors`**

**Comment by GodsDusk** [comment]
Error and Exception Handling

In this advanced Python program challenge, you will need to demonstrate your high-level programming skills by handling errors and exceptions in a complex and practical scenario. The challenge is designed to test your knowledge of error handling, exception management, and ability to anticipate and prevent problems in your code.

This challenge is divided into three sub-challenges, each with a detailed introduction, purpose, and requirements. Make sure to carefully read the instructions and complete the tasks outlined in the "TODO" sections.

## Sub-challenge 1: Custom Exceptions and Logging

### Introduction

In this sub-challenge, you will create custom exception classes for specific error conditions and use the logging module to log exceptions and important events in the application.

### Purpose

This sub-challenge aims to help you understand how to create custom exception classes and use the logging module to record error messages and events for later analysis.

### Requirements

1. Create custom exception classes for the following error conditions:
   - `FileNotFoundError`
   - `InvalidDataError`
   - `OperationFailedError`
2. Set up a logging system to record error messages and events with different log levels (INFO, WARNING, ERROR, and CRITICAL).

#### TODO

1. Implement the custom exception classes mentioned above, inheriting from the `Exception` class.
2. Set up the logging module with an appropriate configuration, including a log file and log format.
3. Raise and handle the custom exceptions at appropriate locations in your code, logging the error messages when exceptions are caught.

## Sub-challenge 2: Graceful Error Recovery

### Introduction

In this sub-challenge, you will implement graceful error recovery mechanisms that allow your program to continue running even when an exception is encountered.

### Purpose

The goal of this sub-challenge is to teach you how to create robust programs that can handle errors and exceptions gracefully without crashing or terminating unexpectedly.

### Requirements

1. Implement a retry mechanism for handling temporary failures.
2. Implement fallbacks for critical operations that cannot be completed due to errors.

#### TODO

1. Identify the parts of your code that may raise temporary exceptions and implement a retry mechanism with exponential backoff.
2. For critical operations, implement fallbacks to ensure your program continues to function even if the operation fails.
3. Use try-except blocks to handle exceptions and recover gracefully from errors.

## Sub-challenge 3: Automated Testing and Error Simulation

### Introduction

In this sub-challenge, you will create automated tests for your program and simulate various error conditions to ensure your error handling mechanisms work as expected.

### Purpose

This sub-challenge aims to teach you how to create comprehensive test cases and simulate error conditions to validate your program's error handling capabilities.

### Requirements

1. Create test cases for your program using the `unittest` module.
2. Simulate error conditions in your test cases to validate your error handling mechanisms.
3. Ensure your test cases cover a wide range of scenarios and edge cases.

#### TODO

1. Write test cases for your program using the `unittest` module.
2. In your test cases, simulate various error conditions to ensure your error handling mechanisms work as expected.
3. Make sure to cover different scenarios and edge cases to test the robustness of your program.

## Conclusion

In this advanced Python program challenge, you have demonstrated your high-level programming skills by handling errors and exceptions in complex scenarios. You have created custom exception classes, implemented graceful error recovery mechanisms, and set up automated testing with error simulation.

By completing this challenge, you have gained a deeper understanding of error handling, exception management, and how to create robust programs that can anticipate and prevent problems.

**Comment by GodsDusk** [comment]
# Solution

## Sub-challenge 1: Custom Exceptions and Logging

```python
import logging
from typing import Any

# Custom exception classes
class FileNotFoundError(Exception):
    """Exception raised when a file is not found."""

class InvalidDataError(Exception):
    """Exception raised when the data is invalid."""

class OperationFailedError(Exception):
    """Exception raised when an operation fails."""


# Set up logging
logging.basicConfig(filename='error_handling_challenge.log',
                    level=logging.INFO,
                    format='%(asctime)s - %(levelname)s - %(message)s')


def read_data_from_file(filename: str) -> Any:
    """
    Read data from a file and return its content.

    :param filename: The name of the file to read.
    :return: The content of the file.
    """
    try:
        with open(filename, 'r') as file:
            data = file.read()
    except FileNotFoundError:
        logging.error(f"File {filename} not found.")
        raise
    return data


def process_data(data: str) -> None:
    """
    Process data and perform an operation.

    :param data: The data to process.
    """
    try:
        if not data:
            raise InvalidDataError("Data is empty.")
        # Perform data processing operation here
    except InvalidDataError as e:
        logging.error(str(e))
        raise


def main() -> None:
    """
    Main function to run the program.
    """
    try:
        data = read_data_from_file('example.txt')
        process_data(data)
    except (FileNotFoundError, InvalidDataError) as e:
        logging.critical("A critical error occurred: " + str(e))


if __name__ == '__main__':
    main()
```

## Sub-challenge 2: Graceful Error Recovery

```python
import time
from typing import Callable

def retry_on_failure(func: Callable, max_retries: int = 3, backoff_factor: float = 2.0) -> Callable:
    """
    Decorator to retry a function on failure with exponential backoff.

    :param func: The function to retry on failure.
    :param max_retries: The maximum number of retries allowed.
    :param backoff_factor: The backoff factor for exponential delay calculation.
    :return: The wrapped function.
    """
    def wrapper(*args, **kwargs):
        retries = 0
        while retries < max_retries:
            try:
                return func(*args, **kwargs)
            except OperationFailedError as e:
                wait_time = backoff_factor ** retries
                logging.warning(f"Operation failed. Retrying in {wait_time} seconds. Error: {str(e)}")
                time.sleep(wait_time)
                retries += 1
        logging.error(f"Operation failed after {max_retries} retries.")
        return None  # Return a fallback value or perform a fallback operation

    return wrapper


@retry_on_failure
def perform_critical_operation(data: str) -> None:
    """
    Perform a critical operation on the data.

    :param data: The data to process.
    """
    try:
        if not data:
            raise OperationFailedError("Data is empty.")
        # Perform critical operation here
    except OperationFailedError as e:
        logging.error(str(e))
        raise


def main() -> None:
    """
    Main function to run the program.
    """
    try:
        data = read_data_from_file('example.txt')
        perform_critical_operation(data)
    except (FileNotFoundError, InvalidDataError) as e:
        logging.critical("A critical error occurred: " + str(e))


if __name__ == '__main__':
    main()
````

## Sub-challenge 3: Automated Testing and Error Simulation

```python
import unittest
from unittest.mock import patch
from io import StringIO

class TestErrorHandlingChallenge(unittest.TestCase):

    def test_read_data_from_file_success(self):
        with patch('builtins.open', new_callable=unittest.mock.mock_open, read_data='example content'):
            result = read_data_from_file('example.txt')
            self.assertEqual(result, 'example content')

    def test_read_data_from_file_failure(self):
        with self.assertRaises(FileNotFoundError):
            read_data_from_file('non_existent_file.txt')

    def test_process_data_success(self):
        try:
            process_data('valid data')
        except InvalidDataError:
            self.fail("process_data() raised InvalidDataError unexpectedly.")

    def test_process_data_failure(self):
        with self.assertRaises(InvalidDataError):
            process_data('')

    def test_perform_critical_operation_success(self):
        with patch('time.sleep'):  # Skip sleep during retry
            try:
                perform_critical_operation('valid data')
            except OperationFailedError:
                self.fail("perform_critical_operation() raised OperationFailedError unexpectedly.")

    def test_perform_critical_operation_failure(self):
        with patch('time.sleep'):  # Skip sleep during retry
            with self.assertRaises(OperationFailedError):
                perform_critical_operation('')

if __name__ == '__main__':
    unittest.main()
```

**Comment by GodsDusk** [comment]
这个challenge比较灵活，建议是把solution中的一部分提供给用户，让用户补完。

测试方法是自己设计各个检测样例，看执行用户完成的功能是否能处理异常以及正确通过
